name: hydra-image
services:
  himage:
    container_name: himage
    image: docker.io/library/himage2:latest
    networks:
      - himage-network
    ports:
      - 5179:5179
    links:
      - himagemongo
    depends_on:
      - himagemongo
    volumes:
      - ../data/uploads:/app/uploads
    environment:
      - IMAGE_DB_HOST=himagemongo
    restart: always

  himagemongo:
    container_name: himagemongo
    image: mongo:latest
    volumes:
      - ../data/db:/data/db:rw
    networks:
      - himage-network
    ports:
      - 27033:27017
    restart: always

networks:
  himage-network:
    driver: bridge
