# kubernetes yaml file for hydra-image
---
apiVersion: v1
kind: Pod
metadata:
  name: hydra-image
  labels:
    app: hydra-image
spec:
  containers:
  - name: mongodb
    image: mongo:4
    container_name: mongodb
    hostNetwork: true
    ports:
      - containerPort: 27017
        hostPort: 27017
        hostIP: 127.0.0.1
    volumeMounts:
      - mountPath: /data/db
        name: mongodb-data
    restartPolicy: unless-stopped

  - name: himage
    image: himage2:2024-12-02
    container_name: himage
    working_dir: /app
    volumeMounts:
      - mountPath: /app/uploads
        name: himage-uploads
    hostNetwork: true    
    ports:
      - containerPort: 5179
        hostPort: 5179
        hostIP: 0.0.0.0
    depends_on:
      - mongodb
    environment:
      - H3PHOTO_SETTINGS={"db":"mongodb"}
    entrypoint: [ "yarn", "start"]
    restartPolicy: unless-stopped

  volumes:
  - name: mongodb-data
    persistentVolumeClaim:
      claimName: mongodb-data

  - name: himage-uploads
    persistentVolumeClaim:
      claimName: himage-uploads
